# Workflow for deploying to Vercel
name: Deploy to Vercel

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Install dependencies
        run: npm install
        
      - name: Build Project
        run: npm run build
        
      - name: Deploy to Vercel
        uses: vercel/action@v21
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          github-comment: false
          
      - name: Debug Deployment
        if: failure()
        run: |
          echo "Deployment failed. Checking project configuration..."
          npm run build || echo "Build failed"
          cat .vercel/project.json || echo "No Vercel project config found"
